### ISSUE TITLE
Another Mac M1 issue

### ISSUE THREAD

**Issue by steps371** [dprint/dprint-plugin-roslyn#12]
I am unable to successfully use the latest plugins on an M1 mac

To reproduce:
* On an M1 mac, run `dprint fmt` with the following as a plugin: `https://plugins.dprint.dev/roslyn-0.13.0.json@2bfa2e67a02b84aa2d23f78ce0f00149cd681078a4a646cf546af804e632e6cf`
* The plugins start downloading, when the following error is produced 
```
Downloading https://github.com/dprint/dprint-plugin-roslyn/releases/download/0.13.0/dprint-plugin-roslyn-aarch64-apple-darwin.zip
```
```
Error resolving plugin https://plugins.dprint.dev/roslyn-0.13.0.json: Failed plugin schema verification. This may indicate you are using an old version of the dprint CLI or plugin and should upgrade.: Could not read success response.: failed to fill whole buffer
```

Other:
* Downloading the executables directly and running from command line doesn't work, and the process gets killed immediately

```
./dprint-plugin-roslyn 
[1]    39029 killed     ./dprint-plugin-roslyn

```
* I have tried to reset dprint cache, which did not resolve the issue

* I am on the latest version of dprint ```dprint 0.36.0```, and get the same issues with previous versions as well

**Comment by LloydNicholson** [comment]
I get exactly the same issue on M1 Mac with 0.41.0 with Roslyn version `https://plugins.dprint.dev/roslyn-0.16.0.json@a508b0823fa356a33b43fc071e1cebe4a9c9ded12ca2f84c46ba67e2a3f13487`

**Comment by LloydNicholson** [comment]
Is there currently a workaround for this issue?

**Comment by dsherret** [comment]
I've been looking into this today because I have access to an M2 now. It was building locally and working for me after this change: https://github.com/dprint/dprint-plugin-roslyn/pull/14

However, I just did a 0.16.1 release and it's not working and it's saying "failed to fill full buffer". I looked into the system logs and found this:

```
$ log show --style syslog --last 1h | grep 'dprint-plugin-roslyn'
...
2023-10-29 21:06:20.529374-0400  localhost kernel[0]: (AppleSystemPolicy) ASP: Security policy would not allow process: 60829, /Users/david/Downloads/dprint-plugin-roslyn-aarch64-apple-darwin/dprint-plugin-roslyn
```

I think maybe I need to codesign the binaries. That would be a pain if so.

**Comment by Phault** [comment]
I was in the same boat with my fork, [dprint-plugin-csharpier](https://github.com/Phault/dprint-plugin-csharpier). Turns out the binaries only get adhoc codesigned, when you build on macOS. 
Simply [switching the GitHub runner to macos-14](https://github.com/Phault/dprint-plugin-csharpier/commit/1cdb8b674ac499e3056f71da585c306bfd0e7dfc), was enough to fix it for me.

See https://github.com/dotnet/sdk/issues/34917 for more details.
